picam_publisher:
  ros__parameters:
    sensor_mode: 1
    src_width: 3280
    src_height: 1848
    src_fps: 21
    out_width: 640
    out_height: 240
    pub_fps: 21.0
    topic: /camera/image_raw
    frame_id: picam

cam_server:
  ros__parameters:
    topic: /vision/line
    host: 0.0.0.0
    port: 8080
    jpeg_quality: 75
