/**:
  ros__parameters:
    red:
      range1:
        h_min: 0
        h_max: 10
        s_min: 80
        s_max: 255
        v_min: 31
        v_max: 255
      range2:
        h_min: 172
        h_max: 180
        s_min: 80
        s_max: 255
        v_min: 80
        v_max: 255
    yellow:
      range1:
        h_min: 15
        h_max: 38
        s_min: 60
        s_max: 255
        v_min: 80
        v_max: 255
    green:
      range1:
        h_min: 45
        h_max: 85
        s_min: 80
        s_max: 255
        v_min: 80
        v_max: 255